language: android
android:
    components:
        - build-tools-22.0.1
        - android-22
        - sys-img-armeabi-v7a-android-22
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
    licenses:
        - android-sdk-license-5be876d5
before_install:
    # Create and start emulator
    - echo no | android create avd --force -n test -t android-22 --abi default/armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - export TERM=dumb
    - ./gradlew -v
    - uname -a
before_script:
  - ./wait_for_emulator
script: ./gradlew clean library:check demo:connectedCheck