language: android
android:
    components:
        - build-tools-19.1.0
before_install:
    # Create and start emulator
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - export TERM=dumb
    - ./gradlew -v
    - uname -a
before_script:
  - wait_for_emulator
script: ./gradlew clean demo:connectedCheck